### ISSUE TITLE
zdi_cpu_instruction_out0 function not working

### ISSUE THREAD

**Issue by envenomator** [S0urceror/AgonElectronHAL#1] opened 2023-04-27 12:58 UTC
Hi Mario,
The zdi_cpu_instruction_out0 function is not working as intended.
According to the ez80f92 documentation, only a single instruction can be written to the ZDI_ISx registers with a maximum of 5 bytes per instruction. The actual instruction is performed by the ez80, as soon as the ZDI_IS0 register is written.
Current code places multiple instructions in the ZDI_ISx registers which are never actually performed by the ez80 because the ZDI_IS0 isn't written to, only ZDI_IS1 and ZDI_IS2. And even then, it can only be a single instruction at a time.

Secondly, the out0 opcode is unstable with the default z80 bus mode, the out opcode should be used.
Below (tested) code fixes this:
void zdi_cpu_instruction_out (uint8_t regnr, uint8_t value) {   
    // ld a, value
    zdi_write_register(ZDI_IS1, value);
    zdi_write_register(ZDI_IS0, 0x3e);
    // out (regnr), a
    zdi_write_register(ZDI_IS1, regnr);
    zdi_write_register(ZDI_IS0, 0xd3);
}

I had fully erased my flash using the Zilog ZDS programmer and then had issues writing/reading to/from 0x40000. Using the 'initialize' function, calls out0 multiple times things still didn't work. Not sure maybe you haven't tested this with a completely uninitialized ez80. I confirm this now works as intended.
Best,
Jeroen

**Comment by S0urceror** [comment] 2023-04-28 07:17
Hi Jeroen,

I know about the single instruction and that it only executes after writing IS0. The current code is like this:
```
void zdi_cpu_instruction_out0 (uint8_t regnr, uint8_t value)
{
    // ld a, nn
    uint8_t instructions[3];
    instructions[0]=value;
    instructions[1]=0x3e;
    zdi_write_registers (ZDI_IS1,2,instructions);
    // out0 (nn),a
    instructions[0]=regnr;
    instructions[1]=0x39;
    instructions[2]=0xed;
    zdi_write_registers (ZDI_IS2,3,instructions);
}
```

LD a,nn is a 2 byte instruction and write_registers starts writing from IS1 and auto-increments to IS0.
OUT0 (nn),a is a 3 byte instruction and here we write and auto-increment from IS2 to IS0.

I built this initially because I kind of bricked my AgonLight after my first flash attempt. Then the RAM/Flash memory is not correctly initialized or not at the expected place. After this init code I was able to reflash and get things going again.

I understood that 'out0' was specifically for writing to the internal registers and 'out' for external devices. I don't mind to use normal 'out' if that makes things more stable.

**Comment by S0urceror** [comment] 2023-04-28 08:22
Also noticed that in MOS it uses out0 all over the place to communicate with the internal registers. Are you sure about the Z80 busmode?

Maybe I need to set more things to a correct initial state after a fully erased flash.

I'll perform a test with this and let you know.

**Comment by envenomator** [comment] 2023-04-28 13:04
I have seen that too. I'll also be checking stuff again this weekend to get to the bottom of this, will keep you posted.

**Comment by envenomator** [comment] 2023-04-28 14:15
I'm sure I got it wrong about the z80 mode. The CS0_BMC is defaulted to 0 at reset. Mos just sets bit 0 to 1 for 1 wait state. That's not it. When I use your (init)code with MOS flashed, I can access 0x40000 / the external memory is mapped by CS0. When the flash is empty or corrupted (and the board is reset), I can sometimes access 0x40000 with your init code, but mostly not. Will do further digging

**Comment by S0urceror** [comment] 2023-04-28 15:54
Well, I wiped my Agon flash. Everything is now 0xFF. And I'm experiencing the same as you. Can't get it back to working with my init code. 

Saw in your code you also initialise CS1, 2 and 3. They are not used but maybe good to not leave them dangling and initialise them as well like in your code.

**Comment by S0urceror** [comment] 2023-04-28 16:06
Think I know what is happening.

When the Flash is wiped it contains 0xFF. This is the RST38 instruction. At 0038h is again 0xFF which calls 0038h again.

The init code sets the stack very high but after all these calls all RAM gets replaced by 000039h which is the address following the RST38.

I have to change my ZDI command line so that it keeps the CPU in break mode and does not auto-continue when you exit ZDI mode.

**Comment by S0urceror** [comment] 2023-04-28 16:23
I can confirm this was the problem indeed. Managed to get my Agon back in order. Btw, I can confirm OUT works just as good as OUT0.

I'll keep this issue open until you can also confirm it's working.

**Comment by envenomator** [comment] 2023-04-28 17:55
Hi,
Using your latest commit, when I'm doing
1) wipe flash
2) Flash the board, then full power cycle
3) 'CTRL-Z' to get into ZDI mode
4) 'i' to initialize using either out or out0 code version
5) 'x 40000' to display memory content

the content is different when I use out or out0; the 'out0' version displays the same value everywhere, mostly all zeroes, where the 'out' version displays actual random memory content.
When I insert another custom 'case' menu option to edit in a single byte, it works fine with just the 'out' version, but doesn't change anything using the 'out0' version. It is like the memory isn't actually mapped in that case.

This exact sequence reproduces the difference in behavior every time for me. Does this happen with your board as well? Maybe it is a hardware issue with mine

[update]
When I'm resetting the board and do the same sequence from 3) as above, the behavior sometimes changes with the 'out0' version. It either displays random memory, or nothing at all. This behavior after reset isn't consistent.

**Comment by S0urceror** [comment] 2023-04-28 19:09
Interesting. I first thought it had something to do with the ADL mode. If it's not on then you cannot use the out0. In Z80 mode you only have the original Z80 instructions.

You know what, we'll leave it just on plain-ol' Z80 out's. If this works and is the most stable then that is it!

**Comment by envenomator** [comment] 2023-04-29 10:24
Thanks for brainstorming together! Yeah, I'm starting to think out0 maybe has issues over the ZDI_ISx interface, just like the datasheet mentions it can't provide generic ADL suffix instruction support because of the 5-byte length maximum. I'm wondering how they even manage to single-step a instruction after loading it over ZDI, while each step shows a huge leap in PC and also A-register changes, even when the ez80 is still in break mode.. Ah well, internal details probably.

I'll open up a query at Zilog and ask if they can shed some light on this, who nows..

**Comment by S0urceror** [comment] 2023-04-30 10:07
Let me know if they do. Maybe just a timing thing. That you cannot change the registers too fast or so. I have updated my code to use regular OUTs as well. Btw. great post and work you did on making it even simpler to use for just uploading firmware without the Zilog cable.

Understand that Dean doesn't want to pollute his code with all kinds of updates but having this type of terminal built-in is actually period-correct (think Apple-IIs) and allow to manipulate the EZ80 in multiple ways.

I'm closing the issue for now.

**Closed as completed by S0urceror** 2023-04-30 10:07 UTC

**Comment by dennowiggle** [comment] 2024-08-27 21:45
I think the solution to the original problem is to issue a zdi reset followed by a zdi break as documented in this recent issue. https://github.com/S0urceror/AgonElectronHAL/issues/4#issuecomment-2313549201

Noting here so hopefully @envenomator will get notification.
